
= Worker REST API

:numbered:

== Overview

This section describes various REST APIs available with the Paro worker.

The following can be passed to the Biometrics API.

* Face photos in JPEG / PNG / BMP / TIFF / JPEG2000 format.
* Iris photos in JPEG / PNG / BMP / TIFF / JPEG2000 / RAW format.
* NEC biometrics template.

Extract biometrics API can accept either photos with each photo having single
iris or photos with multiple faces and hence respond with individual iris/face
information respectively. Search biometrics API can accept either single face
+ mask template or 1 left iris template +1 right iris template and search it
against the specified dataset and return match scores based on configured similarity
threshold. The APIs are designed this way to avoid any ambiguity that might result
in the enrollments and searches with group photos.

The worker may be optionally built to communicate with a license server that grants licenses to
to the Paro worker which will determine which modalities are enabled. If a REST API is called
when a license grant has not been obtained or one has been obtained but the does not
include the modality of the REST API, an error response will be sent.

Enrollments and dataset creation/deletion will be via Kafka topics and enrollments are always
version controlled.The version is always a growing number greater than 0.

JSON is used as the data-interchange format for all the APIs.

The following sections will explain various terms used throughout this document.


== Synchronous and Asynchronous REST APIs

Paro Worker provides synchronous and asynchronous version of several of the REST
APIs. These are: extract, verify, verifyMany, and search. These operations can
take a sufficient amount of time where it can be beneficial to execute them
asynchronously which can help free certain resources in the Paro Manager and
Worker.

The Paro Manager can specify whether the worker should execute the operation
syncrhonously or asynchronously by specifying a `response_endpoint` field in the
body of the request. If this field is not specified, the operation will complete
synchronously. If this field is specified, the operation will complete
asynchronously and the result will be sent by the worker to this location.
Currently, this field can contain valid `http` or `https` URLs. Example:
`"response_endpoint": "http://<paro-manager-address>:8080/paro/v1/asynctest"`

When the synchronous version of one of these APIs is called by the Paro Manager,
the worker will receive the API request, then execute the operation fully, then
send back the response to the Paro Manager. This will block one of the REST API
threads in the worker from processing another request until the current
operation has completed.

When the asynchronous version of one of these APIs is called by the Paro
Manager, the worker will receive the API request and send back an immediate 200
OK response, if the request passes initial validation. A job for the operation
will be queued to a pool of objects that will actually execute the operations
within their respective threads. Once the operation completes within one of
these job handler threads, the response will then be queued to a pool of objects
that will then send the operation result to the location specified in the
initial request. The asynchronous versions of these APIs will prevent the
receiving REST API thread from being blocked while executing the operation, but
operations may not start executing immediately if there are not enough job
handler objects available to process all requests.

Upon startup, a Paro Worker will allocate a fixed number of thread objects to
handle asynchronous requests:

[frame="topbot",options="header",cols="^2,^3,10"]
|====
|Object Type            |Count allocated      |Description

|`AsyncJobExecutor`     |The max value of extract thread count and REST thread count  |This object receives an operation job request that has been queued from a REST handler, and executes that operation within its own thread. When the operation is complete, this object will then queue the response to the pool of AsyncJobResponder objects.

|`AsyncJobResponder`     |The value configured in the ENV variable `PARO_WORKER_ASYNC_RESPONDER_THREAD_COUNT` or 2 if not configured  |This object receives an operation job result queued from an AsyncJobExecuter. It will attempt to send that result to the value specified in the original 'response_endpoint' field. Either an `HTTP` or `HTTPS` connection will be made to that endpoint address and sent via a POST message. There will be up to 2 attempts to deliver the message.

|====
The following sections will explain various terms used throughout this document.

== Position mappings

=== Iris position mapping

|====
|Position       | Description

|`unknown`      | Unknown iris position (only with extract)
|`iris_right`   | Right iris
|`iris_left`    | Left iris

|====

=== Finger Position mapping
=== Finger Position Mapping

|====
| Position                 | Description

| `unknown`                | Unknown finger position (only with extract)
| `roll_right_thumb`       | Right thumb in rolled position
| `roll_right_index`       | Right index finger in rolled position
| `roll_right_middle`      | Right middle finger in rolled position
| `roll_right_ring`        | Right ring finger in rolled position
| `roll_right_little`      | Right little finger in rolled position
| `roll_left_thumb`        | Left thumb in rolled position
| `roll_left_index`        | Left index finger in rolled position
| `roll_left_middle`       | Left middle finger in rolled position
| `roll_left_ring`         | Left ring finger in rolled position
| `roll_left_little`       | Left little finger in rolled position
| `slap_right_four`        | Right four fingers in slap position
| `slap_left_four`         | Left four fingers in slap position
| `slap_thumbs`            | Both thumbs in slap position
| `slap_right_thumb`       | Right thumb in slap position
| `slap_right_index`       | Right index finger in slap position
| `slap_right_middle`      | Right middle finger in slap position
| `slap_right_ring`        | Right ring finger in slap position
| `slap_right_little`      | Right little finger in slap position
| `slap_left_thumb`        | Left thumb in slap position
| `slap_left_index`        | Left index finger in slap position
| `slap_left_middle`       | Left middle finger in slap position
| `slap_left_ring`         | Left ring finger in slap position
| `slap_left_little`       | Left little finger in slap position
|====


The following sections will explain various input and output parameters associated with each modality.

== Input Parameters

=== Face Parameters

The parameters in the request are required by the facial algorithm for detection, extraction and matching.

[frame="topbot",options="header",cols="^2,^3,10"]
|=============================
|Parameter                  |Range      |Description

|`max_eye_distance`         |10 to 1000 |Maximum distance is in pixels. Default value is 1,000.
|`min_eye_distance`         |10 to 400  |Minimum distance is in pixels. Default value is 20.
|`max_face_count`           |1 to 256   |Maximum number of faces to detect in each photo. Default value is 1.
|`reliability`              |0 to 100   |Only faces with `face_score` meeting this threshold will be used for extraction. Default value is 70.
|`detection_algorithm`      |1,2,5,6    |Detection algorithm to use. 1: D10 frontal, 2: D10 side, 5: HD4 normal, 6: HD4 fast. Default value is 5.
|`similarity_threshold`     |0 to 9999  |Similarity score describes how similar the face in the probe photo is to the face in the dataset. 0 implies not similar and 9999 implies highly similar. Persons with similarity scores greater than this threshold will be returned in the response.
|`enable_param_auto_scaling`|true, false|If specified as `true`, `min_eye_distance` and `max_eye_distance` values will be reduced by same amount, the larger image is scaled down from its original resolution(greater than 1000 * 1000 pixels). If specified as `false`, `min_eye_distance` and `max_eye_distance` values will not be altered even though original image is scaled down from its original resolution(greater than 1000 * 1000 pixels).
Default value is `true`.
|`min_eye_distance`         |10 to 280  |The distance is in pixels
|`max_face_count`           |1 to 256   |Maximum number of faces to detect in each photo
|`reliability`              |0 to 100   |Only faces with `face_score` meeting this threshold will be used for extraction. Typically `reliability` can be 70.
|`detection_algorithm`      |1, 5       |Detection algorithm to use. 1: D10 frontal, 2: D10 side, 5: HD4 normal, 6: HD4 fast
|`similarity_threshold`     |0 to 10000 |
Similarity score describes how similar the face in the probe photo is to the face in the dataset. 0 implies not similar and 10000 implies highly similar. Persons with similarity scores greater than this threshold will be returned in the response
|=============================

=== Iris Parameters

The parameters in the request are required by the iris algorithm for matching.

[frame="topbot",options="header",cols="^2,^3,10"]
|====
| Parameter            |Range       |Description

|`similarity_threshold`|0 to 9999   |Similarity score describes how similar the iris in the probe is to the iris in the dataset. 0 implies not similar and 9999 implies highly similar. Persons with similarity scores greater than this threshold will be returned in the response.
|`speed`               |0 to 2      |Speed for extraction or matching: 0 -> Speed Priority Mode, 1 -> Intermediate modes of speed priority and accuracy priority, 2 -> Accuracy Priority Mode. Default value is 2.
|`rotation`            |0 to 180    |The alignment angle search width at the time of matching. Default value is 15.
|`landmark_detect_mode`|0 to 3      |Mode for landmark detection used for extraction: 0 -> Speed Priority Mode, 1 -> Speed Priority Mode for Extract, 2-> Accuracy Priority Mode, 3-> Accuracy Priority Mode for Extract. Default value is 2.
|`match_mode`          |0 to 2      |Mode for dual matching: 0 -> Straight Match Mode, 1 -> Cross Match Mode, 2 -> Hybrid Match Mode. Default value is 0.
|`quality_threshold`   |integer     |NEC Iris minimum quality threshold. Default value is 20
|`usable_area_ratio_threshold`|0 to 100|The ratio of effective iris area.
|`focus_score_threshold`|0 to 100   |Focus Score, the closer it is to 100, the less misalignment.
|`motion_blur_score_threshold`|0 to 100|Motion Blur Score, the closer it is to 100 there is less movement blur.
|`check_liveness_score`|true, false |To check liveness score of iris images during extraction.Default value is false.
|`check_quality_score` |true, false |To check quality score of iris images during extraction.Default value is false.If this setting is enabled, the detected iris or landmark qualities named(usable_area score, motion_blur score & focus_score) will be retrieved and validated against respective threshold values.
If these quality values are greater than respective threshold margins, then those quality values will be outputted
in iris attributes along with iris templates.

|====

== Output Attributes

=== Face Attributes

When a photo is provided, the success response will contain the face attributes as part of the extraction and verify.
If you get the value out of the range like -10399 , it means the library error.

[frame="topbot",options="header",cols="^2,^3,10"]
|====
| Parameter            |Range         |Description

|`face_score`          | 0 to 100     |Measures the faceness of the detected face
|`frontal_face_score`  | 0 to 100     |The measure of how frontal the face is
|`quality`             | 0 to 100     |Estimated quality of the face based on the other face attributes
|`jpg_quality`         | 0 to 100     |Estimated quality of image
|`face_pan`            | -90 to 90    |Pan angle of face in degrees
|`face_roll`           | -30 to 30    |Roll angle of face in degrees
|`face_tilt`           | -40 to 40    |Tilt angle of face in degrees
|`face_rect`           |X-Y coordinate|Rectangle where the face is found in the input image
|`head_rect`           |X-Y coordinate|Rectangle where the head is found in the input image
|`left_eye`            |X-Y coordinate|Point where the left eye is found in the input image
|`right_eye`           |X-Y coordinate|Point where the right eye is found in the input image
|`eye_distance`        |              |Measures the eye distance from the detected face
|`left_eye_closure_score` | 0 to 100  |Measures left eye's closing score of the detected face
|`right_eye_closure_score`| 0 to 100  |Measures right eye's closing score of the detected face
|`smile_score`         | 0 to 100     |Wherein the larger the value, the greater the degree of smiling
|`glass_confidence`    | 0 to 100     |Wherein the larger the value, the greater the degree of wearing glasses
|`sunglass_confidence` | 0 to 100     |Wherein the larger the value, the greater the degree of wearing sunglasses
|`mask_confidence`     | 0 to 100     |Wherein the larger the value, the greater the degree of wearing a mask
|`gaze_vertical`       | -100 to 100  |The angle expressing the vertical gaze angle of the detected face
|`gaze_horizontal`     | -100 to 100  |The angle expressing the horizontal gaze angle of the detected face
|`gender_score`        | 0 to 100     |Wherein the larger the value, the greater the degree of male
|`age`                 | 1 to 99      |The estimated age of the detected face
|`liveness`            | 0 to 100     |The progress rate of the number of frames used for the motion detection

|====

=== Iris Attributes

When a iris is provided, the success response will contain the iris attributes as part of the extraction and verify responses.

[frame="topbot",options="header",cols="^2,^3,10"]
|====
| Parameter             |Range        |Description

|`iris`                 |             |Ellipse information of the iris region.
|`pupil`                |             |Ellipse information of the pupil region.
|`upper_eyelid`         |             |Ellipse information of the Upper eyelid region.
|`lower_eyelid`         |             |Ellipse information of the Lower eyelid region.
|`focus_score`          |0 to 100     |Iris alignment focus score.
|`iris_quality`         |Integer      |Quality information.
|`motion_blur_score`    |0 to 100     | Iris motion blur score.
|`usable_area_ratio`    |0 to 100     |ratio of effective iris area.
|`liveness_score`       |0 to 100     |Calculated liveness score of iris.
|`cosmetic_contact_lens`|0 to 100     |Wearing cosmetic contact lens score.
|====

==== Iris Ellipse Information
[frame="topbot",options="header",cols="^2,^3,10"]
|====
| Parameter             |Range        |Description

|`x`|ShortInteger   |x-coordinate of ellipse center (with coordinates outside the image)
|`y`|Short Integer|y-coordinate of ellipse center (with coordinates outside the image)
|`a`|Unsigned Short Integer|Radius of the ellipse in the x-axis direction (Unit: pixel)
|`b`|Unsigned Short Integer|Radius of the ellipse in the y-axis direction (Unit: pixel)
|`t`|Unsigned Short Integer|The angle formed by the y-axis and the radius b in the y-axis direction

|====

== Show Information

List the information of Paro Worker version.

* Path

    /paro/v1/info

* Method

    GET

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

    NIL

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
  "version": "1.9.0",
  "version_string": "1.9.0 (e8eebfa68194598300bf6ef7a358b5b112324aca, compiled Apr 25 2024 12:09:13)"
}
----

* Error Response

    NIL

* Sample Call
+
[source,bash]
----
curl -k -X GET --header 'Accept: application/json' https://ip:port/paro/v1/info
----

* Notes

== Extract Biometrics

If a `response_endpoint` value is specified in the request, an immediate
response will be returned but the operation will be executed asynchronously and
the actual response will be sent to the location specified in
`response_endpoint` when the operation has completed.

=== Face

Extracts the biometric template data from given photos and returns them as part of response.

* Path

    /paro/v1/extract/face

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
id: [1-36 alphanumeric]
image_format: "jpg" / "png" / "bmp" / "tiff" / "jp2"
photo: [base64]
----

** Optional
+
[source,ini]
----
max_eye_distance: [integer]
min_eye_distance: [integer]
reliability: [integer - 0 to 100]
enable_param_auto_scaling: [bool]
max_face_count: [integer]
detection_algorithm: [integer - 1 to 5]
liveness: [integer]
enable_age: [bool]
enable_gender: [bool]
enable_mask_template: [bool]
auto_mask_template: [bool]
min_mask_threshold: [int]
max_mask_threshold: [int]
response_endpoint: [string]
----

** Sample JSON
+
[source,json]
----
{
    "face_parameters":{
        "max_eye_distance":600,
        "min_eye_distance":30,
        "reliability":80,
        "enable_param_auto_scaling": true,
        "max_face_count":2,
        "detection_algorithm":1,
        "liveness": 34,
        "enable_age": true,
        "enable_gender": true,
        "enable_mask_template": true,
        "auto_mask_template": true,
        "min_mask_threshold": 20,
        "max_mask_threshold": 40
    },
    "photos":[
        {
            "id":"photo-id-1",
            "image_format":"image format",
            "photo":"base64 encoded data",
            "seed":"optional string seed"
        },
        {
            "id":"photo-id-2",
            "image_format":"image format",
            "photo":"base64 encoded data"
            "seed":"optional string seed"
        }
    ]
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "face_templates":[
        {
            "status":{
                "success":true
            },
            "id":"photo-id-1",
            "face_attributes":{
                "face_score":99,
                "frontal_face_score":53,
                "quality":87,
                "jpg_quality":74,
                "face_pan":-5,
                "face_roll":-2,
                "face_tilt":-6,
                "face_rect":{
                    "left":234,
                    "right":326,
                    "top":119,
                    "bottom":211
                },
                "head_rect":{
                    "left":217,
                    "right":341,
                    "top":78,
                    "bottom":228
                },
                "left_eye":{
                    "x":301,
                    "y":139
                },
                "right_eye":{
                    "x":254,
                    "y":143
                },
                "eye_distance":47,
                "left_eye_closure_score":10,
                "right_eye_closure_score":10,
                "smile_score":85,
                "glass_confidence":0,
                "sunglass_confidence":0,
                "mask_confidence":13,
                "gaze_vertical":0,
                "gaze_horizontal":0,
                "gender_score":0,
                "age":0,
                "liveness":0
            },
            "face_template":"base64 encoded data",
            "mask_template":"base64 encoded data"
        },
        {
            "status":{
                "success":false,
                "error":"face not detected"
            },
            "id":"photo-id-2"
        }
    ]
}
----

* Error Response

** Code: 406 NOT ACCEPTABLE
** Content
+
[source,json]
----
{
    "status":{
        "success":false,
        "error":"Invalid parameters."
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/extract/face
----

* Notes
+
Multiple photos can be passed to the API, each identified by a photo ID. The response is populated
with the details of the face templates and face attributes per face in the photo. The photo blob
will be discarded.
+
`max_face_count` is used here so that photos with more than 1 face can be extracted. The response
will contain face attributes, which will in-turn contain head rectangle using which the client app
can plot/associate the faces.


=== Iris
Extracts the biometric template data from given iris image and returns them as part of response.

* Path

    /paro/v1/extract/iris

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
iris_images : [json array  contain below object with mentioned parameters ]
 id: [1-36 alphanumeric]
 image_format: "jpg" / "png" / "bmp" / "tiff" / "jp2" / "raw"
 iris_image: [base64]
 iris_position: [string like iris_left / iris_right / unknown]
----

** Optional
+
[source,ini]
----
job_id : [string]
image_width: [integer]
image_height: [integer]
response_endpoint: [string]
iris_parameters: [ Json object containing array of below key value pairs ]
 speed: [integer]
 landmark_detect_mode: [integer ]
 quality_threshold: [integer ]
 usable_area_ratio_threshold: [integer ]
 focus_score_threshold: [integer ]
 motion_blur_score_threshold: [integer ]
 check_liveness_score: [boolean]
 check_quality_score: [boolean]
----

** Sample JSON
+
[source,json]
----
{
  "job_id": "string",
  "response_endpoint": "string",
  "job_timeout_milli": 0,
  "iris_parameters": {
    "landmark_detect_mode": 1,
    "speed": 2,
    "check_liveness_score": true,
    "check_quality_score": true
  },
  "iris_images": [
    {
      "image_format": "wsq",
      "iris_image": "string",
      "id": "string",
      "image_width": 100,
      "image_height": 120
    }
  ]
}
----
* Success Response

** Code: 200
** Content
+
[source,json]
----
{
  "iris_templates": [
    {
      "id": "RightEyeS5000R00",
      "iris_attributes": {
        "iris": {
          "a": 91,
          "b": 91,
          "t": 0,
          "x": 264,
          "y": 259
        },
        "pupil": {
          "a": 33,
          "b": 33,
          "t": 38384,
          "x": 264,
          "y": 259
        },
        "upper_eyelid": {
          "a": 33,
          "b": 33,
          "t": 38384,
          "x": 264,
          "y": 259
        },
        "lower_eyelid": {
          "a": 91,
          "b": 91,
          "t": 0,
          "x": 264,
          "y": 259
        },
        "quality": {
            "focus_score": 97,
            "iris_quality": 58,
            "motion_blur_score": 66,
            "usable_area_ratio": 100
        },
        "liveness": 22,
        "cosmetic_contact_lens": 0
      },
      "iris_position": "unknown",
      "iris_template": "base64 encoded data",
      "status": {
        "success": true
      }
    }
  ]
}
----
* Error Response

** Code: 200
** Content
+
[source,json]
----
{
    "status":{
        "success":false,
        "error":"NIris: failed to extract iris feature"
    }
}
----
* Error Response

** Code: 400 HTTP BAD REQUEST
** Content
+
[source,json]
----
{
    "status":{
        "success":false,
        "error":"Invalid parameters."
    }
}
----
The error message varies depending on specific parameter which is invalid.
Some examples of error strings as follows:
** error: `id should be specified in the extract request`.
** error: `image_format' should be specified in the extract request for id`.
** error: `iris_image' should be specified in the extract request for id`.
* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/extract/iris
----

* Notes
+
Multiple images can be passed to the API, each identified by an ID. The response is populated
with the details of the iris templates and iris attributes per image.

=== Tenprint finger

=== Latent Finger

Extracts biometric template data from a given latent fingerprint image and returns it as part of the response.

* Path

    /paro/v1/extract/finger/latent

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
job_id: [string]
response_endpoint: [string]
job_timeout_milli: [integer] <int64>
id: [string]
algorithm: [lfml|elfml|nfv3|ht]
image_format: [wsq|jpg|jp2|tiff|png|bmp|raw]
roi: [string <byte>]
----

** Optional
+
[source,ini]
----
edited_nec_inner_template: [string <byte>]
edited_efs_type9_template: [string <byte>]
finger_parameters:
  rotation: [integer <int32>]
quality_only: [boolean]
quality_algos: [array of strings]
  Items Enum: [iql|IQL|nfiq2|NFIQ2]
send_cropped_images: [boolean]
latent_image: [string <byte>]
image_width: [integer <int32>] (only required for raw image format)
image_height: [integer <int32>] (only required for raw image format)
ppi: [integer <int32>]
  Enum: [500|1000]
black_on_white: [boolean]
  Enum: [true|false]
manual_minutiae: [array of objects]
  - x: [integer <int32>]
    y: [integer <int32>]
    angle: [integer <int32>]
    type: [integer <int32>]
efs_data: [string <byte>]
send_skeleton_images: [boolean]
extract_url_part: [string]
----

** Sample JSON
+
[source,json]
----
{
    "job_id": "example-job-id",
    "response_endpoint": "http://HostName/receiveAPI",
    "job_timeout_milli": 10000,
    "id": "example-finger-id",
    "algorithm": "lfml",
    "edited_nec_inner_template": "example-nec-template",
    "edited_efs_type9_template": "example-efs-template",
    "finger_parameters": {
        "rotation": 45
    },
    "quality_only": true,
    "quality_algos": [
        "iql"
    ],
    "send_cropped_images": true,
    "latent_image": "base64_encoded_image",
    "image_format": "wsq",
    "image_width": 400,
    "image_height": 500,
    "ppi": 500,
    "black_on_white": true,
    "roi": "example-roi",
    "manual_minutiae": [
        {
            "x": 150,
            "y": 200,
            "angle": 90,
            "type": 1
        }
    ],
    "efs_data": "example-efs-data",
    "send_skeleton_images": true,
    "extract_url_part": "example-url-part"
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "status": {
        "success": true,
        "code": "200",
        "error": "",
        "error_detail": ""
    },
    "job_id": "example-job-id",
    "id": "example-finger-id",
    "latent_template": "base64_encoded_latent_template",
    "finger_position": "unknown",
    "inner_templates": [
        {
            "index": 0,
            "minutiae_count": 100,
            "data": "base64_encoded_inner_template",
            "algorithm": "lfml"
        }
    ],
    "cropped_finger_images": [
        {
            "finger_position": "unknown",
            "cropped_image_format": "wsq",
            "finger_image": "base64_encoded_cropped_image"
        }
    ],
    "skeleton_image": {
        "bpp": 8,
        "w": 400,
        "h": 500,
        "image": "base64_encoded_skeleton_image"
    },
    "quality": {
        "emi": 90,
        "iql": 85,
        "nfiq2": 2
    }
}
----

* Error Response

** Code: 406 NOT ACCEPTABLE
** Content
+
[source,json]
----
{
    "status": {
        "success": false,
        "code": "406",
        "error": "Invalid parameters.",
        "error_detail": "Detailed error message"
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/extract/finger/latent
----

* Notes
+
- `quality_only` specifies whether only quality metrics are returned.
- `send_cropped_images` indicates whether cropped images should be included in the response.
- `send_skeleton_images` specifies whether skeleton images should be included in the response.
- The `manual_minutiae` array allows the inclusion of manually provided minutiae points.
- The `latent_template` and `inner_templates` fields contain the extracted biometric data in base64 encoding.
- The response includes quality metrics and optional image data, which can be used for further processing or analysis.


=== Tenprint palm

NOTE: Future support.

=== Latent Palm

Extracts biometric template data from a given latent palm image and returns it as part of the response.

* Path

    /paro/v1/extract/palm/latent

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
job_id: [string]
response_endpoint: [string]
job_timeout_milli: [integer] <int64>
id: [string]
algorithm: [lfml|elfml|nfv3|ht]
image_format: [wsq|jpg|jp2|tiff|png|bmp|raw]
roi: [string <byte>]
----

** Optional
+
[source,ini]
----
edited_nec_inner_template: [string <byte>]
edited_efs_type9_template: [string <byte>]
palm_parameters:
  rotation: [integer <int32>]
latent_image: [string <byte>]
image_width: [integer <int32>] (only required for raw image format)
image_height: [integer <int32>] (only required for raw image format)
ppi: [integer <int32>]
  Enum: [500|1000]
black_on_white: [boolean]
  Enum: [true|false]
send_skeleton_images: [boolean]
manual_minutiae: [array of objects]
  - x: [integer <int32>]
    y: [integer <int32>]
    angle: [integer <int32>]
    type: [integer <int32>]
efs_data: [string <byte>]
extract_url_part: [string]
----

** Sample JSON
+
[source,json]
----
{
    "job_id": "example-job-id",
    "response_endpoint": "http://HostName/receiveAPI",
    "job_timeout_milli": 10000,
    "id": "example-palm-id",
    "algorithm": "lfml",
    "edited_nec_inner_template": "example-nec-template",
    "edited_efs_type9_template": "example-efs-template",
    "palm_parameters": {
        "rotation": 45
    },
    "latent_image": "base64_encoded_image",
    "image_format": "wsq",
    "image_width": 400,
    "image_height": 500,
    "ppi": 500,
    "black_on_white": true,
    "roi": "example-roi",
    "send_skeleton_images": true,
    "manual_minutiae": [
        {
            "x": 150,
            "y": 200,
            "angle": 90,
            "type": 1
        }
    ],
    "efs_data": "example-efs-data",
    "extract_url_part": "example-url-part"
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "status": {
        "success": true,
        "code": "200",
        "error": "",
        "error_detail": ""
    },
    "job_id": "example-job-id",
    "id": "example-palm-id",
    "latent_template": "base64_encoded_latent_template",
    "palm_position": "palm_right_full",
    "inner_templates": [
        {
            "index": 0,
            "minutiae_count": 100,
            "data": "base64_encoded_inner_template",
            "algorithm": "lfml"
        }
    ],
    "skeleton_image": {
        "bpp": 8,
        "w": 400,
        "h": 500,
        "image": "base64_encoded_skeleton_image"
    },
    "quality": 85
}
----

* Error Response

** Code: 406 NOT ACCEPTABLE
** Content
+
[source,json]
----
{
    "status": {
        "success": false,
        "code": "406",
        "error": "Invalid parameters.",
        "error_detail": "Detailed error message"
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/extract/palm/latent
----

* Notes
+
- `send_skeleton_images` specifies whether skeleton images should be included in the response.
- The `manual_minutiae` array allows the inclusion of manually provided minutiae points.
- The `latent_template` and `inner_templates` fields contain the extracted biometric data in base64 encoding.
- The response includes quality metrics and optional image data, which can be used for further processing or analysis.


== Reseed Biometrics

=== Face

Reseeds the biometric template data.

* Path

    /paro/v1/face/reseed

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
face_template: "base64 encoded data"
----

** Optional
+
[source,ini]
----
cur_seed: [string]
new_seed: [string]
----

** Sample JSON
+
[source,json]
----
{
    "face_template":"base64 encoded data",
    "cur_seed":"optional string seed",
    "new_seed":"optional string seed"
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "face_template": "base64 encoded data",
    "status": {
        "success": true
    }
}
----

* Error Response

** Code: 400 BAD REQUEST
** Content
+
[source,json]
----
{
    "status": {
        "error": "Neither current seed nor new seed specified in reseed request. At least one must be specified.",
        "success": false
    }
}
----

* Error Response

** Code: 422 UNPROCESSABLE ENTITY
** Content
+
[source,json]
----
{
    "status": {
        "error": "NeoFace: Reseed failed.",
        "success": false
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/face/reseed
----

* Notes
+
This will reseed the template with the seed passed in "new_seed". If
the template has been previously generated with another seed, that seed must be
passed in "cur_seed". To generate a template without a seed, don't pass a value
for "new_seed". Either "cur_seed" or "new_seed" must be present and not a
nullstring.


== Create Dataset

This API creates a dataset with a given ID, type and few other information
pertaining to that. The same dataset ID shall be used in future correspondences.
`dataset_type` will be `face`, `iris` and the `max_template_size` varies with
the dataset type used. `max_event_count` represents the total number of events
expected to be stored in the dataset. Memory (RAM) for datasets will be reserved
based on `max_template_size` and `max_event_count`. Offset ID (explained in the
Enroll Persons section) will be used to enroll the templates into the specific
(array) slots/indexes in the datasets.

* Path

    /paro/v1/datasets

* Method

    POST

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
dataset_id: [alphanumeric, hyphen is allowed]
dataset_type: [ face / iris /...]
max_template_size: 700,
max_event_count: 100000
----

** Optional
+
[source,ini]
----
persist: [boolean, default false]
----

* Sample JSON
** face dataset
+
[source,json]
----
{
    "dataset_id":"flight-123a",
    "dataset_type":"face",
    "persist":true

}
----
** iris dataset
+
[source,json]
----
{
    "dataset_id":"flight-123b",
    "dataset_type":"iris",
    "persist":true

}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "dataset_id":"flight-123a",
    "status":{
        "success":true
    }
}
----

* Error Response

** Code: 405 METHOD NOT ALLOWED
** Content: `NIL`

* Sample Call

[source,bash]
----
curl -k -X POST --data '{"dataset_id":"flight-123a", "dataset_type": "face", "persist": true}' https://ip:port/paro/v1/datasets
----

* Notes

** "dataset_type" can have values like 'iris' for creating iris datasets.

== Show Datasets

List all available datasets.

* Path

    /paro/v1/datasets

* Method

    GET

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

    NIL

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "datasets":[
        {
            "dataset_id":"flight-123a",
            "dataset_type":"face",
            "version":23
        },
        {
            "dataset_id":"1f104455-06d3-47c0-93b1-84e9e50f4e43",
            "dataset_type":"finger_cml",
            "version":4
        },
        {
            "dataset_id":"291deaaf-8ad5-4403-80b0-be48102617a9",
            "dataset_type":"finger_lfml",
            "version":0
        },
        {
            "dataset_id":"1f104455-06d3-47c0-93b1-84e9e50f4e42",
            "dataset_type":"iris",
            "version":5
        }
    ],
    "status":{
        "success":true
    }
}
----

* Error Response

    NIL

* Sample Call
+
[source,bash]
----
curl -k -X GET --header 'Accept: application/json' https://ip:port/paro/v1/datasets
----

* Notes

== Show Persons

List all available person IDs in the given dataset.This is based on DatasetID , not DatasetType.
Hence this API can be used to list persons any kind of Dataset that we need.

* Path

    /paro/v1/datasets/<dataset-id>/persons

* Method

    GET

* Path Parameters

** Required
+
[source,ini]
----
dataset-id: string
----

* Data Parameters

    NIL

* Success Response

** Code: 200
** Content
+
[source,json]
----

----

* Error Response

** Code: 404 NOT FOUND
** Content
+
[source,json]
----
{
    "status":{
        "error":"Dataset not found.",
        "success":false
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X GET --header 'Accept: application/json' https://ip:port/paro/v1/datasets/flight-123a/persons
----

* Notes

== Enroll Persons

Enroll a list of biometric templates of one or more persons into a given dataset. A person can
contain multiple events (eg: multiple photos for the same person) identified by the respective
`eventId`.

Version is supplied by and is managed externally by the client. Paro worker store and return it
for event-sourcing purposes handled in the client layer.

Offset ID will be used to enroll the templates into the specific (array) slots/indexes in
the datasets. It is at the user's discretion to insert the event templates into the appropriate
offset.

`operation` will determine whether the person's event data is inserted or deleted.

TIP: This API supports both insert and delete of events of persons for easier data management.

CAUTION: Use only one client thread to enroll events/persons in the dataset, otherwise the
version being sent across different threads will conflict and might not be desirable.

* Path

    /paro/v1/datasets/{datasetId}/persons/face
    /paro/v1/datasets/{datasetId}/persons/iris

* Method

    POST

* Path Parameters

** Required
+
[source,ini]
----
dataset_id: [alphanumeric, hyphen is allowed]
----

** Optional

    NIL

* Query Parameters

** Required

    NIL

** Optional
+
[source,ini]
----
version: [Positive integer value greater than current version of respective dataset]
----

* Data Parameters

** Required

- Face template registration
+
[source,ini]
----
person_id: [alphanumeric]
event_id: [alphanumeric]
offset_id: [integer]
face_template/mask_template: object of face/mask template
operation: insert/delete
----

- Iris template
+
[source,ini]
----
operation: [ string like 'insert' / 'delete' ]
person_id: [ alphanumeric ]
event_id: [ alphanumeric ]
offset_id: [ integer ]
iris_templates: [ array of below iris template objects confined to maximum of 1 iris_left and 1 iris_right templates ]
"quality" : [ integer ]
"template" : [ base64 encoded iris template ]
"position" : [ string like iris_left / iris_right ]
----

** Optional
+
[source,ini]
----
version: [ integer. this should be specified if version unspecified in query parameter]
gender: [ string ]
yob: [ integer ]
opaque_data: [ string ]
flags: [ string ]
----

* Examples
- Face Template enrollment request
+
[source,json]
----
[
    {
        "person_id": "Jane-Smith",
        "event_id": "2018-05-12",
        "offset_id": 0,
        "operation": "insert",
        "face_template": {
            "quality": 80,
            "template": "base64"
        }
    },
    {
        "person_id": "John-Smith",
        "event_id": "2013-06-26",
        "offset_id": 1,
        "operation": "insert",
        "face_template": {
            "quality": 89,
            "template": "base64"
        }
    },
    {
        "person_id": "John-Smith",
        "event_id": "2018-05-12",
        "offset_id": 2,
        "operation": "insert",
        "face_template": {
            "quality": 94,
            "template": "base64"
        }
    }
]
----

- Iris Template enrollment request
+
[source,json]
----
[
    {
    "operation": "insert",
    "event_id": "string",
    "person_id": "shiva",
    "offset_id": 3,
    "iris_templates": [
        {
            "quality": 0,
            "template": "based64 encoded data",
            "iris_position": "iris_left"
        }
        {
            "quality": 0,
            "template": "based64 encoded data",
            "iris_position": "iris_right"
        }
        ]
    }
]
----

* Success Response

** Code: 200

** Content
+
----
{
    "status": {
        "success": true
    }
}
----

* Error Response

** Code: 404 NOT FOUND
** Content
+
[source,json]
----
{
    "status": {
        "error": "The dataset XYZ does not exist.",
        "success": false
    }
}
----

* Error Response

** Code: 406 NOT Acceptable
** Content
+
[source,json]
----
{
    "status": {
        "error": "invalid operation - operation #1",
        "success": false
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X GET --header 'Accept: application/json' https://ip:port/paro/v1/datasets/{datasetId}/persons/face
curl -k -X GET --header 'Accept: application/json' https://ip:port/paro/v1/datasets/{datasetId}/persons/iris
----

== Show Persons

List all available person IDs in the given dataset.

CAUTION: The response of this API has an array of events per person, just to be consistent
with the response of the Paro-manager (k8s orchestrator).

* Path

    /paro/v1/datasets/{datasetId}/persons

* Method

    GET

* Path Parameters

** Required
+
[source,ini]
----
dataset-id: string
----

* Data Parameters

    NIL

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "status": {
        "success": true
    },
    "persons": [
        {
            "person_id": "string",
            "events": [
                {
                    "event_id": "string",
                    "offset_id": 0
                }
            ]
        },
        {
            "person_id": "string",
            "events": [
                {
                    "event_id": "string",
                    "offset_id": 1
                }
            ]
        }
    ]
}
----

* Error Response

** Code: 404 NOT FOUND
** Content
+
[source,json]
----
{
    "status":{
        "error":"Dataset not found.",
        "success":false
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X GET --header 'Accept: application/json' https://ip:port/paro/v1/datasets/flight-123a/persons
----

* Notes

== Search dataset

Performs biometric matching against a specific dataset with the given template data and returns
the persons exceeding the similarity threshold.

If a `response_endpoint` value is specified in the request, an immediate
response will be returned but the operation will be executed asynchronously and
the actual response will be sent to the location specified in
`response_endpoint` when the operation has completed.

=== Face

Perform biometric matching of given face or mask template against a specific dataset or a set
of target persons. Returns the persons exceeding the similarity threshold.

* Path

    /paro/v1/search/face

* Method

    PUT

* Path Parameters

** Required

    dataset-id: [UUID]

** Optional

    NIL

* Data Parameters

** Required
+
[source,ini]
----
target_datasets: [ array of strings ]
face_template/mask_template: [base64]
----

** Optional
+
[source,ini]
----
reliability: [integer - 0 to 100]
response_endpoint: [string]
----

** Sample Face JSON
+
*** Request with face template
+
[source,json]
----
{
    "target_datasets":[
        "dataset-1",
        "dataset-2"
    ]
    "target_persons":[
        "person-1",
        "person-2"
    ],
    "max_person_count":30,
    "face_search_details":{
        "face_template":"base64 encoded data"
        "mask_template":"base64 encoded data"
    },
    "search_options": {
      "use_prefiltering": true,
      "gender": "male",
      "yob": 0,
      "yob_range": 0,
      "reliability": 0,
      "similarity_threshold": 3000,
      "flags": ""
    }
}
----
*** Success Response
**** Code: 200
**** Content
+
[source,json]
----
{
  "status": {
    "success": true
  },
  "persons": [
    {
      "person_id": "p-1",
      "overall_score": 9999,
      "events": [
        {
          "event_id": "e1",
          "dataset_id": "test_face_1",
          "overall_score": 9999,
          "event_scores": [
            {
              "probe_position": "frontal_face",
              "target_position": "frontal_face",
              "score": 9999
            }
          ]
        },
        {
          "event_id": "e2",
          "dataset_id": "test_face_1",
          "overall_score": 236,
          "event_scores": [
            {
              "probe_position": "frontal_face",
              "target_position": "frontal_face",
              "score": 236
            }
          ]
        }
      ]
    },
    {
      "person_id": "p-2",
      "overall_score": 9999,
      "events": [
        {
          "event_id": "e3",
          "dataset_id": "test_face_1",
          "overall_score": 9999,
          "event_scores": [
            {
              "probe_position": "frontal_face",
              "target_position": "frontal_face",
              "score": 9999
            }
          ]
        }
      ]
    }
  ],
  "statistics": {
    "count": [
      {
        "dataset_id": "test_face_1",
        "event_read_count": 3,
        "template_match_count": 3,
        "template_read_count": 3
      }
    ],
    "search_time": 0
  }
}
----

* Error Response
** Code: 404 NOT FOUND
** Content
+
[source,json]
----
{
    "status":{
        "error":"Dataset not found.",
        "success":false
    }
}
----

** Code: 406 NOT ACCEPTABLE
** Content
+
[source,json]
----
{
    "status":{
        "error":"JSON: Template not found in request.",
        "success":false
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json_search_request https://ip:port/paro/v1/datasets/flight-123a/search/face
----

* Notes

** It must be noted that the response body will not contain attributes if face template is sent for matching.
** When the API that accepts `dataset_id` in the URI is used, `target_datasets` in the body is ignored.

=== Iris

Perform biometric matching of given iris template against a specific dataset or set of datasets or a set of target persons. Returns the persons exceeding the similarity threshold.

* Path

    /paro/v1/search/iris

* Method

    PUT

* Path Parameters

** Required

    NIL

** Optional

    NIL

* Data Parameters

** Required
+
[source,ini]
----
target_datasets: [ array of strings ]
iris_search_details : [Json object containing below key-value pair]
    iris_template_details: [ array of base64 encoded iris template objects ]
        iris_template: [ base64 encoded data ],
        iris_position: [ iris_left/iris_right ]

----

** Optional
+
[source,ini]
----
response_endpoint: [string]
target_persons: [ array of strings ]
max_person_count: [ integer ]
search_options: [json object containing array of following key-value pairs]
    flags: [ string ]
    gender: [ string ]
    yob: [ integer ]
    yob_range: [ integer ]
    similarity_threshold: [ integer range from 0 - 9999]
    use_prefilter: [ boolean ]

"iris_search_options": [json object containing array of following key-value pairs]
    match_mode: 2,
    speed: 2,
    rotation: 128
----

** Sample IRIS JSON
+
*** Request with iris template
+
[source,json]
----
{
  "job_id": "string",
  "response_endpoint": "string",
  "job_timeout_milli": 0,

  "target_datasets": [
    "omagasiya"
  ],
  "target_persons": [
    "shiva"
  ],
  "max_person_count": 10,
  "validate_templates": true,
  "search_options": {
    "flags": "string",
    "gender": "string",
    "yob": 0,
    "yob_range": 0,
    "similarity_threshold": 9999,
    "use_prefilter": true
  },

  "iris_search_options": {
    "match_mode": 2,
    "speed": 2,
    "rotation": 128
  },
  "iris_search_details": {
    "iris_template_details": [
      {
        "iris_template": "base64 encoded data",
        "iris_position": "iris_left"
      },
      {
        "iris_template": "base64 encoded data",
        "iris_position": "iris_right"
      },
      {
        "iris_template": "base64 encoded data",
        "iris_position": "unknown"
      }
    ]
  }
}
----
*** Success Response
**** Code: 200
**** Content
+
[source,json]
----
{
  "persons": [
    {
      "events": [
        {
          "dataset_id": "",
          "event_id": "smp-i1",
          "event_scores": [
            {
              "probe_position": "iris_left",
              "score": 9754,
              "target_position": "iris_left"
            }
          ],
          "opaque_data": "",
          "overall_score": 9754
        },
        {
          "dataset_id": "",
          "event_id": "smp-i2",
          "event_scores": [
            {
              "probe_position": "iris_left",
              "score": 9754,
              "target_position": "iris_left"
            }
          ],
          "opaque_data": "",
          "overall_score": 9754
        }
      ],
      "overall_score": 9754,
      "person_id": "smp-p1"
    },
    {
      "events": [
        {
          "dataset_id": "",
          "event_id": "smp-i3",
          "event_scores": [
            {
              "probe_position": "iris_left",
              "score": 9754,
              "target_position": "iris_left"
            }
          ],
          "opaque_data": "",
          "overall_score": 9754
        }
      ],
      "overall_score": 9754,
      "person_id": "smp-p3"
    }
  ],
  "statistics": {
    "count": [
      {
        "dataset_id": "iris123",
        "event_read_count": 3,
        "template_match_count": 3,
        "template_read_count": 3
      }
    ],
    "extract_time": 0,
    "search_time": 0
  },
  "status": {
    "success": true
  }
}
----

* Error Response
** Code: 404 NOT FOUND
** Content
+
[source,json]
----
{
    "status": {
        "success": false,
        "code": "404",
        "error": "Target dataset not found: omega"
    }
}
----

* Error Response
** Code: 500 Internal Server Error
** Content
+
[source,json]
----
{
    "status": {
        "success": false,
        "error": "JSON: Template not found in request."
    },
    "statistics": {
        "search_time": 0
    }
}
----
* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json_search_request https://ip:port/paro/v1/search/iris
----

* Notes

** It must be noted that the response body will not contain attributes if iris template is sent for matching.

== 1:1 verify

Matches the given face images or features and returns the score.

If a `response_endpoint` value is specified in the request, an immediate
response will be returned but the operation will be executed asynchronously and
the actual response will be sent to the location specified in
`response_endpoint` when the operation has completed.

=== Face

* Path

    /paro/v1/verify/face

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
face_parameters: object
image_format: "jpg" / "png" / "bmp" / "tiff" / "jp2"
photo: [base64]

or

face_template: [base64]
----

** Optional
+
[source,ini]
----
response_endpoint: [string]
auto_mask_template: [bool]
min_mask_threshold: [int]
max_mask_threshold: [int]
enable_param_auto_scaling: [bool]
mask_template: [base64]
----
** Sample JSON
+
*** Face image matched against a face template.
+
[source,json]
----
{
    "face_parameters":{
        "max_eye_distance":600,
        "min_eye_distance":30,
        "reliability":80,
        "enable_param_auto_scaling": false,
        "max_face_count":2,
        "detection_algorithm":1,
        "auto_mask_template": true,
        "min_mask_threshold": 20,
        "max_mask_threshold": 40
    },
    "probe_image_details":{
        "image_format":"image format",
        "photo":"base64 encoded data",
        "seed":"optional string seed"

    },
    "target_template_details":{
        "face_template":"base64 encoded data"
        "mask_template":"base64 encoded data"
    }
}
----
+
*** Face image matched against a face image.
+
[source,json]
----
{
    "face_parameters":{
        "max_eye_distance":600,
        "min_eye_distance":30,
        "reliability":80,
        "enable_param_auto_scaling": true,
        "max_face_count":2,
        "detection_algorithm":1,
        "auto_mask_template": true,
        "min_mask_threshold": 20,
        "max_mask_threshold": 40
    },
    "probe_image_details":{
        "image_format":"image format",
        "photo":"base64 encoded data"
    },
    "target_image_details":{
        "image_format":"image format",
        "photo":"base64 encoded data"
    }
}
----
+
*** Face template matched against a face template.
+
[source,json]
----
{
    "face_parameters":{
        "max_eye_distance":600,
        "min_eye_distance":30,
        "reliability":80,
        "enable_param_auto_scaling": false,
        "max_face_count":2,
        "detection_algorithm":1
    },
    "probe_template_details":{
        "face_template":"base64 encoded data"
        "mask_template":"base64 encoded data"
    },
    "target_template_details":{
        "face_template":"base64 encoded data"
        "mask_template":"base64 encoded data"
    }
}
----
+
*** Face template matched against a face image.
+
[source,json]
----
{
    "face_parameters":{
        "max_eye_distance":600,
        "min_eye_distance":30,
        "reliability":80,
        "enable_param_auto_scaling": true,
        "max_face_count":2,
        "detection_algorithm":1,
        "auto_mask_template": true,
        "min_mask_threshold": 20,
        "max_mask_threshold": 40
    },
    "probe_template_details":{
        "face_template":"base64 encoded data"
        "mask_template":"base64 encoded data"
    },
    "target_image_details":{
        "image_format":"image format",
        "photo":"base64 encoded data",
        "seed":"optional string seed"
    }
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "score":9999,
    "status":{
        "success":true
    }
}
----

* Error Response

** Code: 200 OK
** Content
+
[source,json]
----
{
    "status":{
        "success":false,
        "error":"appropriate error message."
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/verify/face
----

=== Iris

* Path

    /paro/v1/verify/iris

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
image_format: "jpg" / "png" / "bmp" / "tiff" / "jp2" / "raw"
probe_image_details: [object having base64 encoded iris_image ]
target_image_details: [object having base64 encoded iris image ]

or

probe_template_details: [object having base64 encoded iris_template]
target_template_details: [object having base64 encoded iris_template]
----

** Optional
+
[source,ini]
----
response_endpoint: [string]
iris_verify_options: [object having array of verify options like speed, rotation, match_mode etc]
iris_parameters: [object having array of iris parameters like speed]
image_width: [integer]
image_height: [integer]
----

** Sample JSON
+
*** Iris image matched against a Iris template.
+
[source,json]
----
{
    "job_id": "",
    "response_endpoint": "",
    "iris_parameters": {
        "speed": 1
    },
    "iris_verify_options": {
        "speed": 2,
        "match_mode": 2,
        "rotation": 128
    },
    "probe_image_details": {
        "image_format": "jpg",
        "iris_image": "base64 encoded data",
        "iris_position": "iris_left"
    },
    "target_template_details": {
        "iris_template": "base64 encoded data"
    }
}
----

+
*** Iris image matched against a Iris image.
+
[source,json]
----
{
  "job_id": "123",
  "response_endpoint": "",
  "iris_parameters": {
    "speed": 1
  },
  "iris_verify_options": {
    "speed": 2,
    "match_mode":2,
    "rotation": 128
  },
  "probe_image_details": {
    "image_format": "jpg",
    "iris_image": "base64 encoded data",
    "iris_position": "iris_left"
  },
  "target_image_details": {
    "image_format": "jpg",
    "iris_image": "base64 encoded data",
    "iris_position": "iris_left"
  }
}
----
+
*** Iris template matched against a Iris image.
+
[source,json]
----
{
  "job_id": "",
  "response_endpoint": "",
  "job_timeout_milli": 0,
  "iris_parameters": {
    "speed": 1
  },
  "iris_verify_options": {
    "speed": 2,
    "match_mode":2,
    "rotation": 128
  },
  "probe_template_details": {
    "iris_template": "base64 encoded data"
  },
  "target_image_details": {
    "image_format": "jpg",
    "iris_image": "base64 encoded data",
    "id": "",
    "iris_position": "iris_left"
  }
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "event_scores": [
        {
            "probe_position": "iris_left",
            "score": 9786,
            "target_position": "iris_left"
        }
    ],
    "score": 4893,
    "status": {
        "success": true
    }
}
----

+
*** Iris template matched against a Iris template.
+
[source,json]
----
{
  "job_id": "",
  "response_endpoint": "",
  "job_timeout_milli": 0,
  "iris_parameters": {
    "speed": 1
  },
  "iris_verify_options": {
    "speed": 2,
    "match_mode": 2,
    "rotation": 128
  },
  "probe_template_details": {
    "iris_template": "base64 encoded data"
  },
  "target_template_details": {
    "iris_template": "base64 encoded data"
  }
}
----
* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "event_scores": [
        {
            "probe_position": "iris_left",
            "score": 9786,
            "target_position": "iris_left"
        }
    ],
    "score": 4893,
    "status": {
        "success": true
    }
}
----
+
*** Error Response
+

** Code: 200 OK
** Content
+
[source,json]
----
{
    "status":{
        "success":false,
        "error":"appropriate error message."
    }
}
----
+
**** Following are possible error messages based on missing parameter in the request
+
*** `The request should contain either 'probe_image_details' or 'probe_template_details', not both`
*** `The request should contain either 'probe_image_details' or 'probe_template_details`
*** `The request should contain either 'target_image_details' or 'target_template_details', not both`
*** `The request should contain either 'target_image_details' or 'target_template_details`
*** `'image_format' should be specified in 'probe_image_details' of the request`
*** `'iris_image' should be specified in 'probe_image_details' of the request`
*** `'image_format' should be specified in 'target_image_details' of the request`
*** `'iris_image' should be specified in 'target_image_details' of the request`
*** `'iris_template' should be specified in 'probe_template_details' of the request`
*** `'iris_template' should be specified in 'target_template_details' of the request`
* Sample Call
+
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/verify/iris
----

== M:N verify

AKA few:few verify. This API matches the given list of probe and target face templates and returns the scores of
each of these pairs.

NOTE: Score threshold is not applied on the list to filter out the results, as the verification results must be
returned in it's entirety.

If a `response_endpoint` value is specified in the request, an immediate
response will be returned but the operation will be executed asynchronously and
the actual response will be sent to the location specified in
`response_endpoint` when the operation has completed.

=== Face

* Path

    /paro/v1/verifyMany/face

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
probe_id: [string]
face_template: [base64]
----

** Optional
+
[source,ini]
----
job_id: [string]
response_endpoint: [string]
----

** Sample JSON
+
*** Face template matched against a face template.
+
[source,json]
----
{
    "job_id": "job1",
    "probes": [
        {
            "probe_id": "pid1",
            "face_template": "base64 encoded data"
        },
        {
            "probe_id": "pid2",
            "face_template": "base64 encoded data"
        }
    ],
    "targets": [
        {
            "target_id": "tid1",
            "face_template": "base64 encoded data"
        },
        {
            "target_id": "tid2",
            "face_template": "base64 encoded data"
        }
    ]
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "job_id": "job1",
    "scores": [
        {
            "probe_id": "pid1",
            "scores": [
                {
                    "target_id": "tid1",
                    "score": 9999
                },
                {
                    "target_id": "tid2",
                    "score": 8041
                }
            ]
        },
        {
            "probe_id": "pid1",
            "scores": [
                {
                   "target_id": "tid1",
                   "score": 7564
                },
                {
                "target_id": "tid2",
                "score": 2837
                }
            ]
        }
    ],
    "status": {
        "success": true
    }
}
----

* Error Response

** Code: 200 OK
** Content
+
[source,json]
----
{
    "status":{
        "success":false,
        "error":"appropriate error message."
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/verifyMany/face
----

=== Iris

* Path

    /paro/v1/verifyMany/iris

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
probe_id: [string]
iris_template: [base64]
----

** Optional
+
[source,ini]
----
job_id: [string]
response_endpoint: [string]
----

** Sample JSON
+
*** Iris template matched against a iris template.
+
[source,json]
----
{
    "job_id": "job1",
    "probes": [
        {
            "probe_id": "pid1",
            "iris_template": "base64 encoded data"
        },
        {
            "probe_id": "pid2",
            "iris_template": "base64 encoded data"
        }
    ],
    "targets": [
        {
            "target_id": "tid1",
            "iris_template": "base64 encoded data"
        },
        {
            "target_id": "tid2",
            "iris_template": "base64 encoded data"
        }
    ]
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "job_id": "job1",
    "scores": [
        {
            "probe_id": "pid1",
            "scores": [
                {
                    "target_id": "tid1",
                    "score": 9999
                },
                {
                    "target_id": "tid2",
                    "score": 8041
                }
            ]
        },
        {
            "probe_id": "pid1",
            "scores": [
                {
                   "target_id": "tid1",
                   "score": 7564
                },
                {
                "target_id": "tid2",
                "score": 2837
                }
            ]
        }
    ],
    "status": {
        "success": true
    }
}
----

* Error Response

** Code: 200 OK
** Content
+
[source,json]
----
{
    "status":{
        "success":false,
        "error":"appropriate error message."
    }
}
----
+
**** Following are possible error messages based on missing parameter in the request
+
*** `Please specify probes and targets.`

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/verifyMany/iris
----

== Validate templates

=== Face

This API validates the given list of face templates and returns the validation result for each.


* Path

    /paro/v1/validate/face

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
templates: [array]
id: [string]
face_template: [base64]
----

** Optional
+
[source,ini]
----
job_id: [string]
----

** Sample JSON
+
*** Face template matched against a face template.
+
[source,json]
----
{
    "job_id": "job1",
    "templates": [
        {
            "id": "id1",
            "face_template": "base64 encoded data"
        },
        {
            "id": "id2",
            "face_template": "base64 encoded data"
        }
    ]
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "job_id": "job1",
    "results": [
        {
            "id": "id1",
            "status": {
                "success": true
            }
        },
        {
            "id": "id",
            "status": {
                "msg": "Specified template is not valid.",
                "success": false
            }
        }
    ],
    "status": {
        "success": true
    }
}
----

* Error Response

** Code: 200 OK
** Content
+
[source,json]
----
{
    "status":{
        "success": false,
        "error": "appropriate error message."
    }
}
----

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/validate/face
----

=== Iris

This API validates the given list of iris templates and returns the validation result for each.


* Path

    /paro/v1/validate/iris

* Method

    PUT

* Path Parameters

    NIL

* Query Parameters

    NIL

* Data Parameters

** Required
+
[source,ini]
----
templates: [array of objects]
iris_template: [base64]
----

** Optional
+
[source,ini]
----
job_id: [string]
iris_position: [string]
id: [string]
----

** Sample JSON
+
*** Iris templates validation.
+
[source,json]
----
{
    "job_id": "job1",
    "templates": [
        {
            "iris_position": "iris_left",
            "iris_template": "base64 encoded data",
            "id": "1"
        },
        {
            "iris_template": "base64 encoded data",
        }
    ]
}
----

* Success Response

** Code: 200
** Content
+
[source,json]
----
{
    "job_id": "job1",
    "results": [
        {
            "id": "id1",
            "status": {
                "success": true
            }
        },
        {
            "id": "id",
            "status": {
                "msg": "Specified template is not valid.",
                "success": false
            }
        }
    ],
    "status": {
        "success": true
    }
}
----

* Error Response

** Code: 200 OK
** Content
+
[source,json]
----
{
    "status":{
        "success": false,
        "error": "appropriate error message."
    }
}
----

* Possible error messages
** `Template data is missing.`
** `Specified template is not valid`

* Sample Call
+
[source,bash]
----
curl -k -X PUT --header 'Content-Type: application/json' --header 'Accept: application/json' --data @json-file-name https://ip:port/paro/v1/validate/iris
----

